In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Downloads/twitter_training.csv")
df

2401  Borderlands  Positive  \
0      2401  Borderlands  Positive   
1      2401  Borderlands  Positive   
2      2401  Borderlands  Positive   
3      2401  Borderlands  Positive   
4      2401  Borderlands  Positive   
...     ...          ...       ...   
74676  9200       Nvidia  Positive   
74677  9200       Nvidia  Positive   
74678  9200       Nvidia  Positive   
74679  9200       Nvidia  Positive   
74680  9200       Nvidia  Positive   

      im getting on borderlands and i will murder you all ,  
0      I am coming to the borders and I will kill you...     
1      im getting on borderlands and i will kill you ...     
2      im coming on borderlands and i will murder you...     
3      im getting on borderlands 2 and i will murder ...     
4      im getting into borderlands and i can murder y...     
...                                                  ...     
74676  Just realized that the Windows partition of my...     
74677  Just realized that my Mac window partition is ...     
74678  Just realized the windows partition of my Mac ...     
74679  Just realized between the windows partition of...     
74680  Just like the windows partition of my Mac is l...     

[74681 rows x 4 columns]

## Data Cleaning

In [3]:
df1 = df.drop(['2401','Borderlands'], axis = 'columns')
df1

Positive im getting on borderlands and i will murder you all ,
0      Positive  I am coming to the borders and I will kill you...   
1      Positive  im getting on borderlands and i will kill you ...   
2      Positive  im coming on borderlands and i will murder you...   
3      Positive  im getting on borderlands 2 and i will murder ...   
4      Positive  im getting into borderlands and i can murder y...   
...         ...                                                ...   
74676  Positive  Just realized that the Windows partition of my...   
74677  Positive  Just realized that my Mac window partition is ...   
74678  Positive  Just realized the windows partition of my Mac ...   
74679  Positive  Just realized between the windows partition of...   
74680  Positive  Just like the windows partition of my Mac is l...   

[74681 rows x 2 columns]

In [4]:
df1['Positive'].unique()

array(['Positive', 'Neutral', 'Negative', 'Irrelevant'], dtype=object)

In [5]:
df2= df1[df1['Positive']!='Irrelevant']
df2

Positive im getting on borderlands and i will murder you all ,
0      Positive  I am coming to the borders and I will kill you...   
1      Positive  im getting on borderlands and i will kill you ...   
2      Positive  im coming on borderlands and i will murder you...   
3      Positive  im getting on borderlands 2 and i will murder ...   
4      Positive  im getting into borderlands and i can murder y...   
...         ...                                                ...   
74676  Positive  Just realized that the Windows partition of my...   
74677  Positive  Just realized that my Mac window partition is ...   
74678  Positive  Just realized the windows partition of my Mac ...   
74679  Positive  Just realized between the windows partition of...   
74680  Positive  Just like the windows partition of my Mac is l...   

[61691 rows x 2 columns]

In [6]:
df2.columns = ['Sentiments', 'Tweets']
df2

Sentiments                                             Tweets
0       Positive  I am coming to the borders and I will kill you...
1       Positive  im getting on borderlands and i will kill you ...
2       Positive  im coming on borderlands and i will murder you...
3       Positive  im getting on borderlands 2 and i will murder ...
4       Positive  im getting into borderlands and i can murder y...
...          ...                                                ...
74676   Positive  Just realized that the Windows partition of my...
74677   Positive  Just realized that my Mac window partition is ...
74678   Positive  Just realized the windows partition of my Mac ...
74679   Positive  Just realized between the windows partition of...
74680   Positive  Just like the windows partition of my Mac is l...

[61691 rows x 2 columns]

In [7]:
df2.isna().sum()

Sentiments      0
Tweets        571
dtype: int64

In [8]:
df3 =df2.dropna()
df3.isna().sum()

Sentiments    0
Tweets        0
dtype: int64

In [9]:
df3['Sentiments'] = df3['Sentiments'].apply(lambda x: 0 if x=='Neutral' else(1 if x=='Positive' else -1))

/tmp/ipykernel_3863/3533953199.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Sentiments'] = df3['Sentiments'].apply(lambda x: 0 if x=='Neutral' else(1 if x=='Positive' else -1))


In [10]:
df3['Sentiments'].unique()

array([ 1,  0, -1])

In [11]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 61120 entries, 0 to 74680
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Sentiments  61120 non-null  int64 
 1   Tweets      61120 non-null  object
dtypes: int64(1), object(1)
memory usage: 1.4+ MB


## Text Cleaning

In [16]:
import spacy 
nlp = spacy.load("en_core_web_lg")

2022-10-27 19:06:52.883630: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-27 19:06:54.987199: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-27 19:06:54.987262: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-10-27 19:06:55.252065: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-27 19:06:59.287934: W tensorflow/stream_executor/platform/de

In [17]:
import re
from spacy.lang.en.stop_words import STOP_WORDS

In [18]:
def stop_words(text):
    doc = nlp(text)
    
    no_stop_words = [token.text for token in doc if not token.is_stop]
    return " ".join(no_stop_words)         

In [19]:
df3["filtered_tweets"] = df3.Tweets.apply(stop_words)
df3["filtered_tweets"]

/tmp/ipykernel_3863/3134001185.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["filtered_tweets"] = df3.Tweets.apply(stop_words)


0                                    coming borders kill ,
1                             m getting borderlands kill ,
2                            m coming borderlands murder ,
3                         m getting borderlands 2 murder ,
4                           m getting borderlands murder ,
                               ...                        
74676    realized Windows partition Mac like 6 years Nv...
74677    realized Mac window partition 6 years Nvidia d...
74678    realized windows partition Mac 6 years Nvidia ...
74679    realized windows partition Mac like 6 years Nv...
74680    like windows partition Mac like 6 years driver...
Name: filtered_tweets, Length: 61120, dtype: object

In [20]:
df3

Sentiments                                             Tweets  \
0               1  I am coming to the borders and I will kill you...   
1               1  im getting on borderlands and i will kill you ...   
2               1  im coming on borderlands and i will murder you...   
3               1  im getting on borderlands 2 and i will murder ...   
4               1  im getting into borderlands and i can murder y...   
...           ...                                                ...   
74676           1  Just realized that the Windows partition of my...   
74677           1  Just realized that my Mac window partition is ...   
74678           1  Just realized the windows partition of my Mac ...   
74679           1  Just realized between the windows partition of...   
74680           1  Just like the windows partition of my Mac is l...   

                                         filtered_tweets  
0                                  coming borders kill ,  
1                           m getting borderlands kill ,  
2                          m coming borderlands murder ,  
3                       m getting borderlands 2 murder ,  
4                         m getting borderlands murder ,  
...                                                  ...  
74676  realized Windows partition Mac like 6 years Nv...  
74677  realized Mac window partition 6 years Nvidia d...  
74678  realized windows partition Mac 6 years Nvidia ...  
74679  realized windows partition Mac like 6 years Nv...  
74680  like windows partition Mac like 6 years driver...  

[61120 rows x 3 columns]

In [21]:
def clean_tweet(tweet):
    # Delete the @
    tweet = re.sub(r"@[A-Za-z0-9]+", ' ', tweet)
    # Delete URL links
    tweet = re.sub(r"https?://[A-Za-z0-9./]+", ' ', tweet)
    # Just keep letters and important punctuation
    tweet = re.sub(r"[^a-zA-Z.!?']", ' ', tweet)
    # Remove additional spaces
    tweet = re.sub(r" +", ' ', tweet)
    #Remove hashtags
    tweet = re.sub(r"#\S+", "",tweet)
    # Additional Cleaning
    tweet = re.sub(r"(\(.*\))|(\[.*\])", "",tweet) 
    tweet = re.sub(r"\b(\w+)(?:\W+\1\b)+","",tweet)
    tweet = re.sub(r'[^\w\s]', '', tweet)
    return tweet

In [22]:
df3['cleaned_tweets'] = [clean_tweet(tweet) for tweet in df3.filtered_tweets]
df3['cleaned_tweets']

/tmp/ipykernel_3863/2421202975.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['cleaned_tweets'] = [clean_tweet(tweet) for tweet in df3.filtered_tweets]


0                                     coming borders kill 
1                              m getting borderlands kill 
2                             m coming borderlands murder 
3                            m getting borderlands murder 
4                            m getting borderlands murder 
                               ...                        
74676    realized Windows partition Mac like years Nvid...
74677    realized Mac window partition years Nvidia dri...
74678    realized windows partition Mac years Nvidia dr...
74679    realized windows partition Mac like years Nvid...
74680    like windows partition Mac like years drivers ...
Name: cleaned_tweets, Length: 61120, dtype: object

In [23]:
df3

Sentiments                                             Tweets  \
0               1  I am coming to the borders and I will kill you...   
1               1  im getting on borderlands and i will kill you ...   
2               1  im coming on borderlands and i will murder you...   
3               1  im getting on borderlands 2 and i will murder ...   
4               1  im getting into borderlands and i can murder y...   
...           ...                                                ...   
74676           1  Just realized that the Windows partition of my...   
74677           1  Just realized that my Mac window partition is ...   
74678           1  Just realized the windows partition of my Mac ...   
74679           1  Just realized between the windows partition of...   
74680           1  Just like the windows partition of my Mac is l...   

                                         filtered_tweets  \
0                                  coming borders kill ,   
1                           m getting borderlands kill ,   
2                          m coming borderlands murder ,   
3                       m getting borderlands 2 murder ,   
4                         m getting borderlands murder ,   
...                                                  ...   
74676  realized Windows partition Mac like 6 years Nv...   
74677  realized Mac window partition 6 years Nvidia d...   
74678  realized windows partition Mac 6 years Nvidia ...   
74679  realized windows partition Mac like 6 years Nv...   
74680  like windows partition Mac like 6 years driver...   

                                          cleaned_tweets  
0                                   coming borders kill   
1                            m getting borderlands kill   
2                           m coming borderlands murder   
3                          m getting borderlands murder   
4                          m getting borderlands murder   
...                                                  ...  
74676  realized Windows partition Mac like years Nvid...  
74677  realized Mac window partition years Nvidia dri...  
74678  realized windows partition Mac years Nvidia dr...  
74679  realized windows partition Mac like years Nvid...  
74680  like windows partition Mac like years drivers ...  

[61120 rows x 4 columns]

In [46]:
nlp.pipeline

[('tok2vec', <spacy.pipeline.tok2vec.Tok2Vec at 0x7f10007f5f40>),
 ('tagger', <spacy.pipeline.tagger.Tagger at 0x7f100096df40>),
 ('parser', <spacy.pipeline.dep_parser.DependencyParser at 0x7f1000a78b30>),
 ('attribute_ruler',
  <spacy.pipeline.attributeruler.AttributeRuler at 0x7f10007f8a80>),
 ('lemmatizer',
  <spacy.lang.en.lemmatizer.EnglishLemmatizer at 0x7f100076bd40>),
 ('ner', <spacy.pipeline.ner.EntityRecognizer at 0x7f1000a78ac0>)]

### converting text to vectors

In [27]:
df3['vector'] = df3['cleaned_tweets'].apply(lambda text: nlp(text).vector)  

/tmp/ipykernel_3863/2225744087.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['vector'] = df3['cleaned_tweets'].apply(lambda text: nlp(text).vector)


In [28]:
df3

Sentiments                                             Tweets  \
0               1  I am coming to the borders and I will kill you...   
1               1  im getting on borderlands and i will kill you ...   
2               1  im coming on borderlands and i will murder you...   
3               1  im getting on borderlands 2 and i will murder ...   
4               1  im getting into borderlands and i can murder y...   
...           ...                                                ...   
74676           1  Just realized that the Windows partition of my...   
74677           1  Just realized that my Mac window partition is ...   
74678           1  Just realized the windows partition of my Mac ...   
74679           1  Just realized between the windows partition of...   
74680           1  Just like the windows partition of my Mac is l...   

                                         filtered_tweets  \
0                                  coming borders kill ,   
1                           m getting borderlands kill ,   
2                          m coming borderlands murder ,   
3                       m getting borderlands 2 murder ,   
4                         m getting borderlands murder ,   
...                                                  ...   
74676  realized Windows partition Mac like 6 years Nv...   
74677  realized Mac window partition 6 years Nvidia d...   
74678  realized windows partition Mac 6 years Nvidia ...   
74679  realized windows partition Mac like 6 years Nv...   
74680  like windows partition Mac like 6 years driver...   

                                          cleaned_tweets  \
0                                   coming borders kill    
1                            m getting borderlands kill    
2                           m coming borderlands murder    
3                          m getting borderlands murder    
4                          m getting borderlands murder    
...                                                  ...   
74676  realized Windows partition Mac like years Nvid...   
74677  realized Mac window partition years Nvidia dri...   
74678  realized windows partition Mac years Nvidia dr...   
74679  realized windows partition Mac like years Nvid...   
74680  like windows partition Mac like years drivers ...   

                                                  vector  
0      [-1.7016335, 1.4290566, -3.1197999, 1.90368, 3...  
1      [-2.2044702, -1.7279, -3.0211, -0.9304275, -1....  
2      [-2.073725, -1.179941, -3.232575, -2.0643876, ...  
3      [-2.299995, -1.903766, -3.386675, -2.0879025, ...  
4      [-2.299995, -1.903766, -3.386675, -2.0879025, ...  
...                                                  ...  
74676  [-1.801852, 1.1069901, 0.33810902, 0.72596896,...  
74677  [-1.477241, 1.314674, -0.17114554, 0.6752889, ...  
74678  [-1.8295021, 1.3253922, -0.40188995, 0.7616554...  
74679  [-1.4395876, 1.9084574, -1.9507792, -0.1164517...  
74680  [-1.814158, 0.92351997, -0.7561566, 0.41036436...  

[61120 rows x 5 columns]

## Training NLP model

In [29]:
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [30]:
x = df3.vector.values

In [31]:
y = df3.Sentiments

In [32]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=500)

In [33]:
x_train.shape, y_test.shape, y_train.shape, y_test.shape

((48896,), (12224,), (48896,), (12224,))

In [34]:
x_train_2d = np.stack(x_train)
x_test_2d = np.stack(x_test)

In [35]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
x_train_scaled = scaler.fit_transform(x_train_2d)
x_test_scaled = scaler.transform(x_test_2d)

In [36]:
from sklearn.ensemble import RandomForestClassifier 

In [37]:
classifier = RandomForestClassifier()
clf_fit = classifier.fit(x_train_scaled, y_train)

### Prediction

In [38]:
y_test_prediction = clf_fit.predict(x_test_scaled)
y_test_prediction

array([-1, -1,  0, ..., -1, -1,  0])

### Prediction accuracy

In [39]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score(y_test, y_test_prediction)

0.793848167539267

## Testing NLP model

In [81]:
text = "good food"
doc = nlp(text).vector
reshaped_text =  np.reshape(doc,(1,300))
clf_fit.predict(reshaped_text)

array([1])

In [82]:
text = "worst food"
doc = nlp(text).vector
reshaped_text =  np.reshape(doc,(1,300))
clf_fit.predict(reshaped_text)

array([-1])

In [91]:
text = "i go to school by bus"
doc = nlp(text).vector
reshaped_text =  np.reshape(doc,(1,300))
clf_fit.predict(reshaped_text)

array([0])

##### Pranjal Tripathi